### PR TITLE
extended flickr lib

### PR DESCRIPTION
**Pull request by geraldstanje**
i extended your flickr package

### CODE REVIEW

**Comment by manki** [comment]
Thanks for the contribution. Can you please add tests (flickr_test.go) for the new code? I'd hate it if I accidentally broke your code when I make changes in the future.

**Comment by geraldstanje** [comment]
so i close this, upload the test and reopen a new pull request?

**Comment by manki** [comment]
Sorry for not responding earlier. All GitHub notifications were somehow not showing up on my inbox.

I think I have fixed the issue with tests. Please retry your tests and let me know when it's ready to be merged.

**Comment by geraldstanje** [comment]
can you merge this to your branch?

**Comment by geraldstanje** [comment]
thanks i added my tests and created a pull request. can you merge it?

2015-04-17 2:41 GMT+02:00 Kannan <notifications@github.com>:

**Comment by manki** [comment]
Thank you for improving the library. I'll take a look at the patch later today.

**Comment by manki** [comment]
FYI, I am making some style changes to your patch. For example, renaming Ispro -> IsPro, Iconfarm -> IconForm, etc. Apologies for breaking your code that relies on these fields.

**Comment by manki** [comment]
Thanks again for the contribution; your changes have been merged. Please update your client code with new field names -- apologies for the inconvenience.

**Comment by geraldstanje** [comment]
great. can we add a test for push subscribe?

**Comment by manki** [comment]
Oh, I didn't realise there was no test for push subscribe. Adding one would be great.

**Pull request merged**
